name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SOLUTION_BUILD_CONFIGURATION: CI

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: src

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Install dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration %SOLUTION_BUILD_CONFIGURATION% --no-restore /p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration %SOLUTION_BUILD_CONFIGURATION% --no-restore --no-build
