name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore /p:ContinuousIntegrationBuild=true src/PSAsync.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:ContinuousIntegrationBuild=true src/PSAsync.sln
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build src/PSAsync.sln
    - name: Publish
      run: |
        sed "s/{GITHUB_TOKEN}/${{ secret.GITHB_TOKEN }}/" .github/workflows/nuget.config > src/nuget.config
        dotnet nuget push --source github --api-key ${{ secrets.GITHUB_TOKEN }} --force-english-output src/builtPackages/*.nupkg
