name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json /p:ContinuousIntegrationBuild=true src/PSAsync.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:ContinuousIntegrationBuild=true src/PSAsync.sln
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build src/PSAsync.sln
    - name: Publish
      run: dotnet nuget push --source https://nuget.pkg.github.com/aetos382/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --force-english-output src/builtPackages/*.nupkg
