name: .NET Core

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      SOLUTION_BUILD_CONFIGURATION: CI
      LOCALAPPDATA: ${{ env.LOCALAPPDATA }}
      USERPROFILE: ${{ env.USERPROFILE }}

    defaults:
      run:
        shell: pwsh
        working-directory: src

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: check environment variables
      run: Get-ChildItem -LiteralPath env:/

    - name: cache nuget packages
      uses: actions/cache@v2
      env:
        cache-prefix: nuget-http-caches-
      with:
        path:
          - ${{ env.LOCALAPPDATA }}/NuGet/v3-cache
          - ${{ env.USERPROFILE }}/.nuget/packages
        key: ${{ env.cache-prefix }}${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ env.cache-prefix }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        # setup-dotnet は global.json からバージョン情報を取得できるが、rollForward や allowPrerelease は解釈しないようなので、明示的に指定する。
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration ${env:SOLUTION_BUILD_CONFIGURATION} --no-restore /p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration ${env:SOLUTION_BUILD_CONFIGURATION} --no-restore --no-build

    - name: check environment variables
      run: Get-ChildItem -Path env:/
