name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  BUILD_CONFIGURATION: CI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore --locked-mode src/PSAsync.sln
    - name: Build
      run: dotnet build --configuration ${BUILD_CONFIGURATION} --no-restore /p:ContinuousIntegrationBuild=true src/PSAsync.sln
    - name: Test
      run: dotnet test --configuration ${BUILD_CONFIGURATION} --no-restore --no-build src/PSAsync.sln
