name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SOLUTION_FILE: src/PSAsync.sln
  SOLUTION_FBUILD_CONFIGURATION: CI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore --locked-mode ${SOLUTION_FSOLUTION_FILE}
    - name: Build
      run: dotnet build --configuration ${SOLUTION_FBUILD_CONFIGURATION} --no-restore /p:ContinuousIntegrationBuild=true ${SOLUTION_FILE}
    - name: Test
      run: dotnet test --configuration ${SOLUTION_FBUILD_CONFIGURATION} --no-restore --no-build ${SOLUTION_FILE}
